### ISSUE TITLE
ToDo for 27/10/2017

### ISSUE THREAD

**Issue by earowang** [earowang/icon#1]
- [ ] Improve documentations for `fa()` and `ai()` (e.g. include references)
- [x] Improve README
- [x] Add xaringan slides as an example to the package for tomorrow's presentation (also serves as a vignette)
- [ ] Add some input checks
